### ISSUE TITLE
layaair2-plus-cmd ui -d 报错

### ISSUE THREAD

**Issue by CZJ000** [Cola-Zhang/layaair2-cmd-plus#5]
nternal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Function.FileTools.getPath (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:72261:26)
    at Function.FileManager.getPath (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:74394:49)
    at Function.CodeManager.exportGameConfig (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:62903:28)
    at Function.CodeManager.createByDir (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:62739:16)
    at Function.CodeManager.exportCode (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:62057:16)
    at Function.ExportManager.exportUICodeWork (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:64340:16)
    at Function.ExportManager.doExportLater (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:64218:19)
    at LayaAirCmdTool.__proto.openProject (/usr/local/lib/node_modules/layaair2-cmd-plus-master/ProjectExportTools/LayaAirCmdTool.max.js:124218:18)

**Comment by chenenyu** [comment]
还维护吗？

**Comment by webbrain-one** [comment]
Hi! I opened [PR #6](https://github.com/Cola-Zhang/layaair2-cmd-plus/pull/6) to address this. It fixes the `ui -d` crash by preventing the path argument from being `undefined` before it’s passed to `path.join`, which should resolve the `ERR_INVALID_ARG_TYPE` error.
